# Theme from terminal.sexy base-16/Tomorrow
[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[colors.normal]
black = "0x1d1f21"
red = "0xcc6666"
green = "0xb5bd68"
yellow = "0xf0c674"
blue = "0x81a2be"
magenta = "0xb294bb"
cyan = "0x8abeb7"
white = "0xc5c8c6"

[colors.bright]
black = "0x969896"
red = "0xcc6666"
green = "0xb5bd68"
yellow = "0xf0c674"
blue = "0x81a2be"
magenta = "0xb294bb"
cyan = "0x8abeb7"
white = "0xffffff"


